modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
# The modid of the mod
modId="barrels_2012" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Barrels 2012" #mandatory
logoFile="barrels_2012.png" #optional
authors="EERussianguy" #optional
description='''
An addon for TFC.
'''
[[dependencies.barrels_2012]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.barrels_2012]] #optional
    modId="curios" #mandatory
    mandatory=true #mandatory
    versionRange="[5.4.2,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.barrels_2012]] #optional
    modId="tfc" #mandatory
    mandatory=true #mandatory
    versionRange="[3.1.3-beta,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.barrels_2012]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
